# Generated by Django 3.0 on 2022-05-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
