# Generated by Django 3.0 on 2022-05-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20220524_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Usuario está ativo'),
        ),
    ]
